files:
  - source: /src/locales/en.json
    translation: /src/locales/%two_letters_code%.json
    update_option: update_without_changes
commit_message: 'New translations: %original_file_name% (%language%)'
append_commit_message:
