#!/bin/sh
# This script runs before each commit.

# Run build command
pnpm run build

# Check if build command was successful
if [ $? -ne 0 ]; then
  echo "Build failed. Aborting commit."
  exit 1
fi

# Run formatting checks
pnpm run format

# Check if formatting checks passed
if [ $? -ne 0 ]; then
  echo "Formatting failed. Aborting commit."
  exit 1
fi

# Run linting checks
pnpm run lint

# Check if linting checks passed
if [ $? -ne 0 ]; then
  echo "Linting failed. Aborting commit."
  exit 1
fi

# # Run tests
# pnpm run test

# # Check if tests passed
# if [ $? -ne 0 ]; then
#   echo "Tests failed. Aborting commit."
#   exit 1
# fi

# If all checks pass, allow the commit to proceed
exit 0
