#!/bin/sh
# This script runs before each commit.

# Debugging: Output message to terminal
echo "Running pre-commit hook..."

# Install dependencies
pnpm install

# Run build command
pnpm run build

# Check if build command was successful
if [ $? -ne 0 ]; then
  echo "Build failed. Aborting commit."
  exit 1
fi

# Run formatting checks
pnpm run format

# Check if formatting checks passed
if [ $? -ne 0 ]; then
  echo "Formatting failed. Aborting commit."
  exit 1
fi

# Run linting checks
pnpm run lint

# Check if linting checks passed
if [ $? -ne 0 ]; then
  echo "Linting failed. Aborting commit."
  exit 1
fi

echo "All checks passed. Committing..."
# If all checks pass, allow the commit to proceed
git push origin HEAD
echo "Pushed to origin HEAD"
exit 0
